### ISSUE TITLE
HLS Streaming

### ISSUE THREAD

**Issue by dbroadhurst** [anthonykgross/docker-broadcaster#2]
I would like to post an HLS stream to the broadcaster and allow other users to watch the stream using HLS. Is this possible with this container?

**Comment by anthonykgross** [comment]
Hey mate,

Yes you could change the configuration for Nginx. Instead to stream to
other streaming services, you can keep your stream and convert it in HLS.
You have to install and configure Nginx and use =>
http://nginx.org/en/docs/http/ngx_http_hls_module.html

Thanks for your interest. Don't hesitate to push your changes.



-----------------------------------------------------------------------------------------------------------------

*Anthony GROSS*
DEVELOPER & FREELANCE
Software engineer at Pepperstone Melbourne, Australia

Email  : anthony.k.gross@gmail.com
Site     : AnthonyKGross.fr

**Comment by anthonykgross** [comment]
HLS and MPEG DASH are now supported
