### ISSUE TITLE
How to set streaming quality?

### ISSUE THREAD

**Issue by Tythus** [anthonykgross/docker-broadcaster#5]
Or what are the streaming qualities?

**Comment by anthonykgross** [comment]
Hi, 

The streaming qualities is pretty good (720p). You can change it up to you. Edit **STREAM_SPECIFIER** and define the quality according FFMPEG documentation : https://ffmpeg.org/ffmpeg-utils.html#Video-size

Let me know if I can help you more, 

Thank you for your interest

**Comment by Tythus** [comment]
oh I mean like to change the bitrate/framerate?

**Comment by anthonykgross** [comment]
@Tythus https://github.com/anthonykgross/docker-broadcaster/blob/dd5e1a65a0925ed1c7ec7b07c2d0567484908dbd/conf/nginx/nginx.conf#L63 Enjoy mate !

**Comment by Tythus** [comment]
I tried changing that after cloneing then running via docker-compose up -d am I missing a step here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anthonykgross** [comment]
Did you clean your docker cache ? It should work !

**Comment by Tythus** [comment]
I have run "docker rm -f $(docker ps -a -q)" then "docker rmi $(docker images -q)" is there anything else? I won't pretend I'm some docker god. All I am doing is git clone the folder nano editing the line in the file you mentioned then "running docker-compose up -d" in the root folder with the compose file

**Comment by anthonykgross** [comment]
Oh sorry my bad : you're perfectly right ! To update the image, you've to build it again.

Use the Makefile : 
1. make build
2. make run

**Comment by Tythus** [comment]
nope did this it is still not changing it

**Comment by anthonykgross** [comment]
It's weird ! I did it on my local and it works : 
- I edited `nginx.conf` and changed `preset ultrafast`
- make build
- make run
- I streamed from OBS to the given URL
- Read the live on VLC

In the metadata stream windows, I can see the changes !

**Comment by Tythus** [comment]
I changed the bitrate and there was no change it still streamed at 2mbps

**Comment by anthonykgross** [comment]
Ok maybe I found an issue. It comes from the new Docker versions. 
Currently, when you run your container with Docker Compose, it is running mine (from the Docker Registry); not your local one. 

Change the `docker-compose.yml` : 

from 
```
broadcaster:
  image: anthonykgross/docker-broadcaster
```
to
```
broadcaster:
  image: anthonykgross/docker-broadcaster:master
```

And 

```
# apply your changes in conf/nginx/nginx.conf. i.e : Replace "2000" by "1000"
$ make build
$ make run
```

Let me know mate ! :)

**Comment by anthonykgross** [comment]
@Tythus is it fixed ?
